'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import AuthGuard from '../../../components/AuthGuard';
import FederationShell,{useFederationData,availability,workers,saveBookings} from '../../../components/FederationShell';
import {phase13,phase12,Lang,t} from '../../../locales';
import {readVerification} from '../../../lib/profiles';
import {notifyBooking} from '../../../lib/notifications';
import {updateBooking,readBookings} from '../../../lib/store';
function C(){const {bookings,setBookings}=useFederationData();const params=useSearchParams();const [lang,setLang]=useState<Lang>('en'),[selectedId,setSelectedId]=useState(params.get('booking')||'');useEffect(()=>setLang((localStorage.getItem('sahyogsetu-language')||'en') as Lang),[params]);const d=phase13[lang]||phase13.en;const items=(t[lang]||t.en).services.items;
 const unassigned=bookings.filter(b=>!b.workerId&&b.status!=='COMPLETED'&&b.status!=='CANCELLED');
 const selected=bookings.find(b=>b.id===selectedId)||unassigned[0];
 const eligible=useMemo(()=>{if(!selected)return[];return workers.map(w=>{const p=readVerification(w.id);const av=availability(w.id,bookings);const skill=w.service===selected.service;const area=p.serviceAreas.some((a:string)=>String(selected.location||'').toLowerCase().includes(a.toLowerCase())||String(selected.location||'').toLowerCase().includes('pune'));return {...w,p,av,skill,area,ok:av!=='OFFLINE'&&skill&&area}}).filter(x=>x.ok)},[selected,bookings]);
 function assign(w:any){if(!selected)return;const result=updateBooking(selected.id,{workerId:w.id,worker:w.name,workerRating:w.rating,workerExperience:w.experience,status:'ASSIGNED'});if(!result.ok)return;const updated=result.next;setBookings(readBookings());notifyBooking('WORKER_ASSIGNED',updated,{customer:true,worker:true,federation:true});}
 return <section className="mx-auto max-w-7xl px-4 py-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-black">{d.assignment}</h1><p className="mt-1 text-sm text-slate-500">{d.selectWorker}</p></div><Link href="/federation/requests" className="rounded-xl border bg-white px-4 py-3 text-sm font-bold">{d.requests}</Link></div>
 <div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.4fr]"><div className="rounded-2xl border bg-white p-4"><h2 className="font-black">{d.unassignedRequests}</h2><div className="mt-3 space-y-2">{unassigned.map(b=><button key={b.id} onClick={()=>setSelectedId(b.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id===b.id?'border-green-400 bg-green-50':''}`}><p className="text-xs text-slate-500">{b.id}</p><p className="font-bold">{items[b.service]||b.service}</p><p className="text-xs text-slate-500">{b.location} · {b.time}</p></button>)}{!unassigned.length&&<p className="py-8 text-center text-sm text-slate-500">{d.noData}</p>}</div></div>
 <div className="rounded-2xl border bg-white p-5">{selected?<><div className="border-b pb-4"><p className="text-xs text-slate-500">{selected.id}</p><h2 className="text-xl font-black">{items[selected.service]||selected.service}</h2><p className="mt-1 text-sm text-slate-500">{selected.requirement} · {selected.location}</p><p className="mt-2 text-sm font-bold">{d.skill}: {items[selected.service]||selected.service}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{eligible.map(w=><article key={w.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-black">{w.name}</p><p className="text-sm text-slate-500">{items[w.service]||w.service} · {w.p.experience} {d.experience}</p></div><span className="text-sm font-black">★ {w.rating}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span>{d.skillMatch}: {w.skill?'✓':'—'}</span><span>{d.areaMatch}: {w.area?'✓':'—'}</span><span>{d.currentWorkload}: {w.av}</span><span>{d.distance}: {w.distance} km</span></div><div className="mt-3 flex gap-2"><Link href={`/workers/${w.id}`} className="rounded-lg border px-3 py-2 text-xs font-bold">{d.viewProfile}</Link><button onClick={()=>assign(w)} className="rounded-lg bg-[#16834b] px-3 py-2 text-xs font-black text-white">{d.assign}</button></div></article>)}{!eligible.length&&<p className="py-10 text-center text-sm text-slate-500">{d.noWorkers}</p>}</div></>:<p className="text-sm text-slate-500">{d.selectWorker}</p>}</div></div></section>}
export default function Assignment(){return <AuthGuard role="federation"><FederationShell><C/></FederationShell></AuthGuard>}
