'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import NotificationBell from '../../components/NotificationBell';
import AuthGuard from '../../components/AuthGuard';
import { languages, Lang, t, phase6 } from '../../locales';
import { logoutDemo, readAuth } from '../../lib/auth';
import { workers } from '../../data/workers';
import { readReviews } from '../../lib/reviews';
import {notifyBooking} from '../../lib/notifications';
import {readBookings,saveBookings,updateBooking,syncEstimateFromBooking} from '../../lib/store';
import {startServiceAfterEstimateApproval} from '../../lib/estimateActions';

type Status='REQUESTED'|'ASSIGNED'|'ACCEPTED'|'ON THE WAY'|'ARRIVED'|'INSPECTION'|'ESTIMATE'|'SERVICE'|'COMPLETED';
type Booking=Record<string, any> & {id:string;status:Status;service:string;workerId?:string};
const KEY='sahyogsetu_bookings';
const availabilityKey=(id:string)=>`sahyogsetu_worker_availability_${id}`;
const rejectedKey=(id:string)=>`sahyogsetu_worker_rejections_${id}`;
const money=(n:number)=>`₹${Math.round(n||0).toLocaleString('en-IN')}`;
const timeline:Status[]=['REQUESTED','ASSIGNED','ACCEPTED','ON THE WAY','ARRIVED','INSPECTION','ESTIMATE','SERVICE','COMPLETED'];

function WorkerContent(){
 const [lang,setLang]=useState<Lang>('en'),[workerId,setWorkerId]=useState('w1'),[available,setAvailable]=useState(true),[bookings,setBookings]=useState<Booking[]>([]),[selected,setSelected]=useState<Booking|null>(null),[notice,setNotice]=useState('');
 const [recentReviews,setRecentReviews]=useState<any[]>([]),[inspectionNotes,setInspectionNotes]=useState(''),[finding,setFinding]=useState(''),[labor,setLabor]=useState(''),[materials,setMaterials]=useState(''),[estimateNotes,setEstimateNotes]=useState('');
 const d={...((t as any)[lang]),worker:{...(t.en as any).worker,...((t as any)[lang]).worker},footer:{...(t.en as any).footer,...((t as any)[lang]).footer}}; const p6=(phase6 as any)[lang];
 function load(){const auth=readAuth();const id=auth.user?.workerId||'w1';setWorkerId(id);setAvailable(localStorage.getItem(availabilityKey(id))!=='false');try{setBookings(readBookings());setRecentReviews(readReviews().slice(0,3))}catch{setBookings([])}}
 useEffect(()=>{const l=localStorage.getItem('sahyogsetu-language') as Lang|null;if(l&&languages[l])setLang(l);load();setRecentReviews(readReviews().slice(0,3));const timer=window.setInterval(load,1000);return()=>window.clearInterval(timer)},[]);
 function changeLang(v:Lang){setLang(v);localStorage.setItem('sahyogsetu-language',v)}
 const profile=workers.find(w=>w.id===workerId)||workers[0];
 const rejected=useMemo(()=>{try{return JSON.parse(localStorage.getItem(rejectedKey(workerId))||'[]') as string[]}catch{return[]}},[workerId,bookings]);
 const requests=bookings.filter(b=>b.status==='REQUESTED'&&b.service===profile.service&&(!b.workerId||b.workerId===profile.id)&&!rejected.includes(b.id));
 const active=bookings.find(b=>b.workerId===workerId&&['ASSIGNED','ACCEPTED','ON THE WAY','ARRIVED','INSPECTION','ESTIMATE','SERVICE'].includes(b.status))||null;
 const completed=bookings.filter(b=>b.workerId===workerId&&b.status==='COMPLETED');
 function persist(next:Booking[]){saveBookings(next);setBookings(readBookings())}
 function update(id:string,patch:Partial<Booking>){const result=updateBooking(id,patch);if(!result.ok)return;setBookings(readBookings());setSelected(s=>s&&s.id===id?result.next:s);if(patch.status&&patch.status!==result.before.status){const map:any={'ACCEPTED':'BOOKING_ACCEPTED','ON THE WAY':'WORKER_ON_THE_WAY','ARRIVED':'WORKER_ARRIVED','INSPECTION':'INSPECTION_STARTED','SERVICE':'SERVICE_STARTED','COMPLETED':'SERVICE_COMPLETED'};if(map[patch.status])notifyBooking(map[patch.status],result.next,{customer:true,worker:false,federation:true});}}
 function setAvailability(v:boolean){setAvailable(v);localStorage.setItem(availabilityKey(workerId),String(v))}
 function accept(b:Booking){const assigned=updateBooking(b.id,{status:'ASSIGNED',workerId:profile.id,worker:profile.name,workerRating:profile.rating,workerExperience:profile.experience});if(!assigned.ok)return;notifyBooking('WORKER_ASSIGNED',assigned.next,{customer:true,worker:false,federation:true});setTimeout(()=>{const accepted=updateBooking(b.id,{status:'ACCEPTED'});if(accepted.ok){notifyBooking('BOOKING_ACCEPTED',accepted.next,{customer:true,worker:false,federation:true});setAvailable(false);localStorage.setItem(availabilityKey(profile.id),'false');setBookings(readBookings());setSelected(accepted.next)}},450)}
 function reject(b:Booking){if(!confirm(d.worker.rejectQuestion))return;const key=rejectedKey(workerId);localStorage.setItem(key,JSON.stringify([...rejected,b.id]));setSelected(null);load()}
 function startTravel(){if(active)update(active.id,{status:'ON THE WAY'})}
 function arrive(){if(active?.status==='ON THE WAY')update(active.id,{status:'ARRIVED',arrivedAt:new Date().toISOString()})}
 function startInspection(){if(active?.status==='ARRIVED'){setInspectionNotes(active.inspectionNotes||'');setFinding(active.findings||'');update(active.id,{status:'INSPECTION'})}}
 function submitEstimate(){if(!active)return;const l=Number(labor)||0,m=Number(materials)||0;if(l<0||m<0||l+m<=0){setNotice(d.worker.estimateInvalid||'Enter a valid estimate greater than zero.');return}update(active.id,{status:'ESTIMATE',inspectionNotes:inspectionNotes.trim(),findings:finding.trim(),inspectionCharge:100,laborCost:l,materialCost:m,estimateTotal:l+m,estimateNotes:estimateNotes.trim(),estimateCreatedAt:new Date().toISOString(),estimateAccepted:null,customerDecision:'PENDING'});setNotice(d.worker.estimateSent||'Estimate sent to customer.');setTimeout(()=>setNotice(''),2500)}
 function startService(){if(!active)return;const result=startServiceAfterEstimateApproval(active.id);if(!result.ok){setNotice('Customer approval is required before starting service.');setTimeout(()=>setNotice(''),2500);return}setBookings(readBookings());setSelected(result.next);setNotice(p6.serviceStarted);setTimeout(()=>setNotice(''),2500)}
 function completeService(){if(!active||active.status!=='SERVICE')return;if(!confirm(p6.completionQuestion))return;update(active.id,{status:'COMPLETED',completedAt:new Date().toISOString()});setAvailable(true);localStorage.setItem(availabilityKey(workerId),'true');setNotice(p6.serviceCompleted);setTimeout(()=>setNotice(''),2500)}
 function logout(){logoutDemo();window.location.replace('/')}
 return <main className="min-h-screen bg-slate-50">
  <header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-5 lg:px-8"><Link href="/" className="text-lg font-black text-[#16834b] sm:text-xl">SahyogSetu</Link><div className="flex items-center gap-2"><span className="hidden rounded-full bg-green-50 px-3 py-2 text-xs font-bold text-[#16834b] sm:inline">{profile.name}</span><NotificationBell/><Link href="/worker/profile" className="rounded-xl border px-3 py-2 text-xs font-bold">{d.worker.profile}</Link><select aria-label={d.footer.language} value={lang} onChange={e=>changeLang(e.target.value as Lang)} className="max-w-24 rounded-lg border px-1 py-2 text-xs">{Object.entries(languages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><Link href="/worker/jobs" className="hidden rounded-xl border px-3 py-2 text-xs font-bold sm:inline">{p6.workerHistory}</Link><button onClick={logout} className="rounded-xl border px-3 py-2 text-xs font-bold sm:text-sm">{d.worker.logout}</button></div></div></header>
 <section className="mx-auto max-w-7xl px-4 py-5 sm:px-5 lg:px-8"><div className="rounded-3xl bg-[#12251f] p-5 text-white shadow-soft sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-green-300">{d.worker.home}</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{profile.name}</h1><p className="mt-1 text-sm text-white/70">{d.services.items[profile.service as keyof typeof d.services.items]} · {profile.experience} {d.worker.experience}</p></div><button onClick={()=>setAvailability(!available)} className={`flex w-full items-center justify-center gap-2 rounded-2xl px-5 py-3 font-black sm:w-auto ${available?'bg-green-500/20 text-green-200':'bg-white/10 text-white/80'}`}><span className={`h-3 w-3 rounded-full ${available?'bg-green-400':'bg-slate-400'}`}/>{available?d.worker.available:d.worker.offline}</button></div></div>
 {notice&&<div role="status" className="mt-4 rounded-2xl bg-green-50 p-4 text-sm font-bold text-[#16834b]">{notice}</div>}
 <div className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section><div className="flex items-center justify-between gap-3"><h2 className="text-2xl font-black">{d.worker.newRequests}</h2><Link href="/worker/jobs" className="text-sm font-bold text-[#16834b] sm:hidden">{p6.workerHistory}</Link></div><div className="mt-4 space-y-3">{requests.map(b=><article key={b.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><span className="inline-flex rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-700">{d.worker.requested}</span><h3 className="mt-3 text-lg font-black">{d.services.items[b.service as keyof typeof d.services.items]}</h3><p className="mt-1 text-sm text-slate-600">{b.requirement}</p><p className="mt-2 text-sm font-semibold text-slate-500">📍 {b.location} · {b.time}</p></div><button onClick={()=>setSelected(b)} className="rounded-xl bg-[#16834b] px-4 py-3 text-sm font-bold text-white">{d.worker.viewRequest}</button></div></article>)}</div>{!requests.length&&<div className="mt-4 rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">{d.worker.noRequests}</div>}
 <section className="mt-8"><h2 className="text-2xl font-black">{d.worker.activeJob}</h2>{active?<div className="mt-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">{d.worker.bookingId}: {active.id}</p><h3 className="mt-1 text-xl font-black">{d.services.items[active.service as keyof typeof d.services.items]}</h3></div><span className="rounded-full bg-green-50 px-3 py-1.5 text-xs font-black text-[#16834b]">{active.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><p className="rounded-xl bg-slate-50 p-3 text-sm"><b>{d.worker.customer}:</b> {active.customer}</p><p className="rounded-xl bg-slate-50 p-3 text-sm"><b>{d.worker.location}:</b> {active.location}</p><p className="rounded-xl bg-slate-50 p-3 text-sm"><b>{d.worker.date}:</b> {active.date}</p><p className="rounded-xl bg-slate-50 p-3 text-sm"><b>{d.worker.time}:</b> {active.time}</p></div>
 {active.status==='ACCEPTED'&&<button onClick={startTravel} className="mt-4 w-full rounded-xl bg-[#16834b] px-5 py-3.5 font-black text-white">{d.worker.startTravel}</button>}
 {active.status==='ON THE WAY'&&<button onClick={arrive} className="mt-4 w-full rounded-xl bg-[#16834b] px-5 py-3.5 font-black text-white">{d.worker.arrived}</button>}
 {active.status==='ARRIVED'&&<button onClick={startInspection} className="mt-4 w-full rounded-xl bg-[#16834b] px-5 py-3.5 font-black text-white">{d.worker.startInspection}</button>}
 {active.status==='INSPECTION'&&<div className="mt-5 space-y-4 rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{d.worker.inspection}</h3><textarea value={inspectionNotes} onChange={e=>setInspectionNotes(e.target.value)} rows={4} className="w-full rounded-xl border bg-white p-3" placeholder={d.worker.inspectionPlaceholder}/><input value={finding} onChange={e=>setFinding(e.target.value)} className="w-full rounded-xl border bg-white p-3" placeholder={d.worker.findingsPlaceholder}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">{d.worker.labor}<input inputMode="decimal" value={labor} onChange={e=>setLabor(e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-3" placeholder="₹ 0"/></label><label className="text-sm font-bold">{d.worker.materials}<input inputMode="decimal" value={materials} onChange={e=>setMaterials(e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-3" placeholder="₹ 0"/></label></div><label className="text-sm font-bold">{d.worker.estimateNotes}<textarea value={estimateNotes} onChange={e=>setEstimateNotes(e.target.value)} rows={3} className="mt-1 w-full rounded-xl border bg-white p-3"/></label><div className="rounded-xl bg-white p-4 text-sm"><span className="font-bold">{d.worker.total}: </span>{money((Number(labor)||0)+(Number(materials)||0))}<span className="ml-2 text-slate-500">· {d.worker.inspectionCharge}: ₹100</span></div><button onClick={submitEstimate} className="w-full rounded-xl bg-[#16834b] px-5 py-3.5 font-black text-white">{d.worker.createEstimate}</button></div>}
 {active.status==='ESTIMATE'&&<div className="mt-5 rounded-2xl bg-green-50 p-4"><h3 className="font-black">{d.worker.estimate}</h3><p className="mt-2 text-sm">{d.worker.total}: <b>{money(active.estimateTotal)}</b></p><p className="text-sm">{d.worker.inspectionCharge}: ₹100</p><p className="mt-2 text-sm font-bold">{active.customerDecision==='ACCEPTED'?p6.estimateAccepted:active.customerDecision==='REJECTED'?d.worker.estimateRejected:d.worker.awaitingCustomer}</p>{active.customerDecision==='ACCEPTED'&&<button onClick={startService} className="mt-4 w-full rounded-xl bg-[#16834b] px-5 py-3.5 font-black text-white">{p6.startService}</button>}{active.customerDecision==='REJECTED'&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{d.worker.estimateRejected}</p>}</div>}
 {active.status==='SERVICE'&&<div className="mt-5 rounded-2xl border border-green-100 bg-green-50 p-5"><p className="text-xs font-black uppercase tracking-wide text-[#16834b]">{p6.service}</p><h3 className="mt-1 text-2xl font-black">{p6.serviceInProgress}</h3><p className="mt-3 text-sm">{p6.acceptedEstimate}: <b>{money(active.estimateTotal)}</b></p><p className="text-sm">{p6.inspectionCharge}: {p6.notAddedSeparately}</p><button onClick={completeService} className="mt-5 w-full rounded-xl bg-[#16834b] px-5 py-3.5 font-black text-white">{p6.markCompleted}</button></div>}
 </div>:<div className="mt-4 rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">{d.worker.noActive}</div>}</section></section>
 <aside className="space-y-5"><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">{d.worker.profile}</h2><div className="mt-4 flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-green-50 text-4xl">{profile.avatar}</div><div><h3 className="font-black">{profile.name}</h3><p className="text-sm text-slate-500">{d.services.items[profile.service as keyof typeof d.services.items]}</p></div></div><div className="mt-5 grid gap-2 text-sm"><p>★ {profile.rating} · {profile.reviews} {d.worker.reviews}</p><p>{profile.experience} {d.worker.experience}</p><p>✓ {d.worker.verified}</p><p>📍 {profile.cooperative}</p></div></section><section className="rounded-2xl border bg-white p-5"><h3 className="font-black">{d.worker.completedJobs}</h3><p className="mt-2 text-3xl font-black text-[#16834b]">{completed.length}</p><p className="mt-1 text-xs text-slate-500">{d.worker.demo}</p></section><section className="rounded-2xl border bg-white p-5"><h3 className="font-black">{p6.review}</h3>{recentReviews.filter(r=>r.workerId===profile.id).length?<div className="mt-3 space-y-3">{recentReviews.filter(r=>r.workerId===profile.id).map(r=><div key={r.reviewId} className="rounded-xl bg-slate-50 p-3"><p className="font-black">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</p>{r.feedback&&<p className="mt-1 text-sm text-slate-600">{r.feedback}</p>}</div>)}</div>:<p className="mt-2 text-sm text-slate-500">{p6.awaitingReview}</p>}</section></aside></div></section>
 {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-0 sm:items-center sm:p-5"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-slate-500">{selected.id}</p><h2 className="mt-1 text-2xl font-black">{d.worker.jobDetails}</h2></div><button onClick={()=>setSelected(null)} className="rounded-lg border px-3 py-2">×</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[[d.worker.service,d.services.items[selected.service as keyof typeof d.services.items]],[d.worker.requirement,selected.requirement],[d.worker.customer,selected.customer],[d.worker.location,selected.location],[d.worker.date,selected.date],[d.worker.time,selected.time]].map(([a,b])=><div key={a} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{a}</p><p className="font-bold">{b}</p></div>)}</div>{selected.status==='REQUESTED'&&<div className="mt-6 flex gap-3"><button onClick={()=>accept(selected)} className="flex-1 rounded-xl bg-[#16834b] px-4 py-3 font-bold text-white">{d.worker.accept}</button><button onClick={()=>reject(selected)} className="flex-1 rounded-xl border px-4 py-3 font-bold">{d.worker.reject}</button></div>}</div></div>}
 </main>
}
export default function WorkerPage(){return <AuthGuard role="worker"><WorkerContent/></AuthGuard>}
