export type NotificationRole='customer'|'worker'|'trainee'|'federation';
export type NotificationType='BOOKING_CREATED'|'BOOKING_CANCELLED'|'WORKER_ASSIGNED'|'BOOKING_ACCEPTED'|'WORKER_ON_THE_WAY'|'WORKER_ARRIVED'|'INSPECTION_STARTED'|'ESTIMATE_READY'|'ESTIMATE_ACCEPTED'|'ESTIMATE_REJECTED'|'SERVICE_STARTED'|'SERVICE_COMPLETED'|'REVIEW_RECEIVED'|'TRAINING_UPDATE'|'FEDERATION_ALERT'|'SYNC_UPDATE'|'SYSTEM'|'PAYMENT_SUCCESSFUL'|'PAYMENT_FAILED'|'INVOICE_AVAILABLE';
export type Notification={id:string;userId:string;role:NotificationRole;type:NotificationType;title:string;message:string;bookingId?:string;read:boolean;createdAt:string};
export const NOTIFICATIONS_KEY='sahyogsetu_notifications';
export function readNotifications():Notification[]{if(typeof window==='undefined')return [];try{return JSON.parse(localStorage.getItem(NOTIFICATIONS_KEY)||'[]')}catch{return []}}
export function saveNotifications(list:Notification[]){localStorage.setItem(NOTIFICATIONS_KEY,JSON.stringify(list))}
export function notify(input:Omit<Notification,'id'|'read'|'createdAt'>){const list=readNotifications();const id=input.bookingId?`${input.type}-${input.bookingId}-${input.userId}`:`${input.type}-${input.userId}-${Date.now()}`;if(list.some(n=>n.id===id))return;list.unshift({id,...input,read:false,createdAt:new Date().toISOString()});saveNotifications(list)}
export function notifyBooking(type:NotificationType,booking:any, extra?:{customer?:boolean;worker?:boolean;federation?:boolean}){const customerId=booking.customerId||'CU-001';const workerId=booking.workerId; if(extra?.customer!==false)notify({userId:customerId,role:'customer',type,title:type,message:type,bookingId:booking.id}); if(extra?.worker&&workerId)notify({userId:workerId.toUpperCase(),role:'worker',type,title:type,message:type,bookingId:booking.id}); if(extra?.federation)notify({userId:booking.federationId||'FED-001',role:'federation',type,title:type,message:type,bookingId:booking.id});}
export function markRead(id:string){saveNotifications(readNotifications().map(n=>n.id===id?{...n,read:true}:n))}
export function markAllRead(userId:string,role:NotificationRole){saveNotifications(readNotifications().map(n=>n.userId===userId&&n.role===role?{...n,read:true}:n))}
export function relativeTime(iso:string){const d=Date.now()-new Date(iso).getTime();const m=Math.floor(d/60000);if(m<1)return 'Just now';if(m<60)return `${m} min ago`;const h=Math.floor(m/60);if(h<24)return `${h} hour${h>1?'s':''} ago`;const days=Math.floor(h/24);return days===1?'Yesterday':`${days} days ago`}
