'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import AuthGuard from '../../../components/AuthGuard';
import FederationShell,{useFederationData,availability,workers,saveBookings} from '../../../components/FederationShell';
import {phase13,phase12,Lang,t} from '../../../locales';
import {notifyBooking} from '../../../lib/notifications';

const filters=['ALL','REQUESTED','UNASSIGNED','ASSIGNED','ACCEPTED','ON THE WAY','ARRIVED','INSPECTION','ESTIMATE','SERVICE','COMPLETED','CANCELLED'];
const labelMap:any={'REQUESTED':'new','UNASSIGNED':'unassigned','ASSIGNED':'assigned','ACCEPTED':'accepted','ON THE WAY':'onTheWay','ARRIVED':'arrived','INSPECTION':'inspection','ESTIMATE':'estimatePending','SERVICE':'service','COMPLETED':'completed','CANCELLED':'cancelled'};
function Content(){const {bookings}=useFederationData();const [lang,setLang]=useState<Lang>('en'),[filter,setFilter]=useState('ALL'),[q,setQ]=useState('');useEffect(()=>setLang((localStorage.getItem('sahyogsetu-language')||'en') as Lang),[]);const d=phase13[lang]||phase13.en;const serviceItems=(t[lang]||t.en).services.items;
 const rows=useMemo(()=>bookings.filter(b=>{const unassigned=!b.workerId;const state=filter==='UNASSIGNED'?unassigned:filter==='ALL'||b.status===filter;const text=[b.id,b.service,b.worker,b.location,b.customerName,b.requirement].join(' ').toLowerCase();return state&&(!q||text.includes(q.toLowerCase()))}),[bookings,filter,q]);
 return <section className="mx-auto max-w-7xl px-4 py-6 sm:px-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">{d.requests}</h1><p className="mt-1 text-sm text-slate-500">{rows.length} {d.totalRequests.toLowerCase()}</p></div><Link href="/federation/assignment" className="rounded-xl bg-[#16834b] px-4 py-3 text-sm font-black text-white">{d.assignment}</Link></div>
 <div className="mt-5 flex flex-wrap gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={d.search} className="min-w-[260px] flex-1 rounded-xl border bg-white px-4 py-3"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border bg-white px-4 py-3">{filters.map(x=><option key={x} value={x}>{x==='ALL'?d.all:x==='UNASSIGNED'?d.unassigned:d[labelMap[x]]||x}</option>)}</select></div>
 <div className="mt-5 overflow-hidden rounded-2xl border bg-white"><div className="divide-y">{rows.map(b=><article key={b.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold text-slate-500">{b.id}</p><h2 className="mt-1 text-lg font-black">{serviceItems[b.service]||b.service}</h2><p className="mt-1 text-sm text-slate-500">{b.location||d.area} · {b.time||'—'}</p><p className="mt-2 text-sm">{b.requirement}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{b.status}</span>{b.priority&&<span className="rounded-full border px-3 py-1 text-xs font-black">{b.priority}</span>}</div></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><span className="text-slate-500">{d.worker}: </span><b>{b.worker||d.unassigned}</b></div><div><span className="text-slate-500">{d.skill}: </span><b>{serviceItems[b.service]||b.service}</b></div><div><span className="text-slate-500">{d.created}: </span><b>{b.createdAt?new Date(b.createdAt).toLocaleString():d.noData}</b></div></div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/federation/requests/${b.id}`} className="rounded-xl border px-4 py-2 text-sm font-bold">{d.viewRequest}</Link>{!b.workerId&&<Link href={`/federation/assignment?booking=${encodeURIComponent(b.id)}`} className="rounded-xl bg-[#16834b] px-4 py-2 text-sm font-bold text-white">{d.assignWorker}</Link>}</div></article>)}</div>{!rows.length&&<div className="p-10 text-center text-sm text-slate-500">{d.noData}</div>}</div></section>}
export default function Requests(){return <AuthGuard role="federation"><FederationShell><Content/></FederationShell></AuthGuard>}
