'use client';
import {useEffect,useMemo,useState} from 'react';
import AuthGuard from '../../../components/AuthGuard';
import FederationShell,{useFederationData,workers} from '../../../components/FederationShell';
import {phase8,t,languages,Lang} from '../../../locales';
import {trainees} from '../../../data/trainees';
import {readReviews} from '../../../lib/reviews';
import FederationMap from '../../../components/FederationMap';
import {filteredBookings,Period,csvEscape} from '../../../lib/analytics';

const serviceKeys=['plumbing','electrical','carpentry','painting','cleaning','gardening','appliance','other'];
const statuses=['REQUESTED','ASSIGNED','ACCEPTED','ON THE WAY','ARRIVED','INSPECTION','ESTIMATE','SERVICE','COMPLETED'];
const areas=['Kothrud','Shivajinagar','Baner','Hadapsar','Wakad'];
const activeStatuses=statuses.filter(s=>s!=='COMPLETED');
type AnalyticsBooking = { workerId?: string; status: string; service?: string; location?: string; createdAt?: string; id: string; worker?: string; estimateTotal?: number };
function availability(id:string,bookings:AnalyticsBooking[]){if(typeof window!=='undefined'&&localStorage.getItem(`sahyogsetu_worker_availability_${id}`)==='false')return 'OFFLINE';if(bookings.some(b=>b.workerId===id&&activeStatuses.includes(b.status)))return 'BUSY';return 'AVAILABLE'}
function Card({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-[#16834b]">{value}</p></div>}
function Content(){
 const {bookings}=useFederationData(); const [lang,setLang]=useState<Lang>('en'); const [period,setPeriod]=useState<Period>('all'); const [service,setService]=useState('all'); const [mapFilter,setMapFilter]=useState('all'); const [reviews,setReviews]=useState<any[]>([]);
 useEffect(()=>{const load=()=>{const l=localStorage.getItem('sahyogsetu-language') as Lang|null;if(l&&languages[l])setLang(l);setReviews(readReviews())};load();window.addEventListener('sahyogsetu-lang-change',load);const i=setInterval(load,1000);return()=>{window.removeEventListener('sahyogsetu-lang-change',load);clearInterval(i)}},[]);
 const d=phase8[lang]||phase8.en; const base=useMemo(()=>filteredBookings(bookings,period,service),[bookings,period,service]);
 const completed=base.filter(b=>b.status==='COMPLETED').length; const active=base.filter(b=>activeStatuses.includes(b.status)).length; const completion=base.length?Math.round(completed/base.length*100):0;
 const avg=reviews.length? (reviews.reduce((a,r)=>a+Number(r.rating||0),0)/reviews.length).toFixed(1):'0.0';
 const counts=serviceKeys.map(k=>({k,n:base.filter(b=>b.service===k).length})); const max=Math.max(1,...counts.map(x=>x.n));
 const statusCounts=statuses.map(s=>({s,n:base.filter(b=>b.status===s).length}));
 const workerStats=workers.map(w=>({w,status:availability(w.id,bookings),completed:bookings.filter(b=>b.workerId===w.id&&b.status==='COMPLETED').length,active:bookings.filter(b=>b.workerId===w.id&&activeStatuses.includes(b.status)).length}));
 const areaStats=areas.map(a=>({a,workers:workers.filter(w=>w.cooperative.toLowerCase().includes(a.toLowerCase())||w.name==='Ramesh Patil'&&a==='Kothrud').length,requests:base.filter(b=>String(b.location||'').toLowerCase().includes(a.toLowerCase())).length,completed:base.filter(b=>b.status==='COMPLETED'&&String(b.location||'').toLowerCase().includes(a.toLowerCase())).length}));
 const alerts=[base.filter(b=>b.status==='REQUESTED'&&!b.workerId).length?`${base.filter(b=>b.status==='REQUESTED'&&!b.workerId).length} ${d.unassignedAlert}`:'',workerStats.filter(x=>x.status==='OFFLINE').length?`${workerStats.filter(x=>x.status==='OFFLINE').length} ${d.unavailableAlert}`:'',base.filter(b=>b.status==='ESTIMATE'&&!b.customerDecision).length?`${base.filter(b=>b.status==='ESTIMATE'&&!b.customerDecision).length} ${d.awaitingAlert}`:''].filter(Boolean);
 const points=base.map((b,i)=>({lat:18.49+(i%5)*.012,lng:73.82+(i%5)*.018,label:b.id,kind:b.status==='COMPLETED'?'completed':b.status==='REQUESTED'?'request':'active'})); workerStats.forEach((x,i)=>points.push({lat:18.51+(i%4)*.015,lng:73.84+(i%4)*.017,label:x.w.name,kind:'worker'}));
 const visiblePoints=mapFilter==='all'?points:points.filter(p=>mapFilter==='workers'?p.kind==='worker':mapFilter==='serviceRequests'?p.kind==='request':mapFilter==='active'?p.kind==='active':p.kind==='completed');
 function exportCsv(){const rows=[['Date','Booking ID','Service','Area','Worker','Status','Estimate','Rating']];base.forEach(b=>rows.push([b.createdAt||'',b.id,b.service,b.location||'',b.worker||'',b.status,b.estimateTotal||'',reviews.find(r=>r.bookingId===b.id)?.rating||''] as any));const blob=new Blob([rows.map(r=>r.map(csvEscape).join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='sahyogsetu-regional-report.csv';a.click();URL.revokeObjectURL(url)}
 return <section className="mx-auto max-w-7xl px-4 py-6 sm:px-5 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[#16834b]">{d.analytics}</p><h1 className="text-3xl font-black">{d.regionalOperations}</h1></div><button onClick={exportCsv} className="rounded-xl bg-[#16834b] px-4 py-3 text-sm font-black text-white">{d.exportReport}</button></div>
 <div className="mt-5 flex flex-wrap gap-2"><select value={period} onChange={e=>setPeriod(e.target.value as Period)} className="rounded-xl border bg-white px-3 py-2 text-sm"><option value="all">{d.allTime}</option><option value="today">{d.today}</option><option value="week">{d.thisWeek}</option><option value="month">{d.thisMonth}</option></select><select value={service} onChange={e=>setService(e.target.value)} className="rounded-xl border bg-white px-3 py-2 text-sm"><option value="all">{d.allServices}</option>{serviceKeys.map(k=><option key={k} value={k}>{t[lang].services.items[k]}</option>)}</select></div>
 <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6"><Card label={d.totalRequests} value={base.length}/><Card label={d.activeJobs} value={active}/><Card label={d.completedJobs} value={completed}/><Card label={d.availableWorkers} value={workerStats.filter(x=>x.status==='AVAILABLE').length}/><Card label={d.averageRating} value={`${avg} ★`}/><Card label={d.activeTrainees} value={trainees.filter(x=>x.trainingStatus==='IN TRAINING').length}/></div>
 {alerts.length>0&&<section className="mt-6 rounded-2xl border bg-amber-50 p-5"><h2 className="font-black">{d.alerts}</h2><div className="mt-3 grid gap-2 sm:grid-cols-3">{alerts.map(a=><div key={a} className="rounded-xl bg-white/80 p-3 text-sm font-semibold">{a}</div>)}</div></section>}
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">{d.serviceDemand}</h2><div className="mt-5 space-y-4">{counts.map(x=><div key={x.k}><div className="flex justify-between text-sm font-bold"><span>{t[lang].services.items[x.k]}</span><span>{x.n}</span></div><div className="mt-1 h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-[#16834b]" style={{width:`${x.n/max*100}%`}}/></div></div>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">{d.jobStatus}</h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{statusCounts.map(x=><div key={x.s} className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-bold text-slate-500">{x.s}</p><p className="mt-1 text-xl font-black">{x.n}</p></div>)}</div><div className="mt-5 rounded-xl bg-green-50 p-4"><p className="text-sm font-bold">{d.completionRate}</p><p className="mt-1 text-3xl font-black text-[#16834b]">{completion}%</p><p className="text-xs text-slate-500">{completed} / {base.length} {d.totalBookings.toLowerCase()}</p></div></section></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">{d.regionalDemand}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{areaStats.map(x=><div key={x.a} className="rounded-xl border p-4"><p className="font-black">{x.a}</p><p className="mt-2 text-sm text-slate-600">{d.workersCount}: {x.workers} · {d.requests}: {x.requests}</p><p className="text-sm text-slate-600">{d.completed}: {x.completed}</p></div>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">{d.workerPerformance}</h2><div className="mt-4 space-y-2">{workerStats.map(x=><div key={x.w.id} className="grid grid-cols-[1fr_auto_auto] gap-3 rounded-xl bg-slate-50 p-3 text-sm"><div><p className="font-black">{x.w.name}</p><p className="text-xs text-slate-500">{t[lang].services.items[x.w.service]} · {x.w.experience}y</p></div><span>★ {x.w.rating}</span><span className="font-bold">{x.status}</span></div>)}</div></section></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">{d.ratingOverview}</h2><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-green-50 p-4"><p className="text-xs text-slate-500">{d.averageRating}</p><p className="text-3xl font-black">{avg} ★</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{d.totalReviews}</p><p className="text-3xl font-black">{reviews.length}</p></div></div><div className="mt-4 space-y-2">{[5,4,3,2,1].map(n=><div key={n} className="flex items-center gap-2 text-sm"><span>{n} ★</span><div className="h-2 flex-1 rounded bg-slate-100"><div className="h-2 rounded bg-[#16834b]" style={{width:`${reviews.length?reviews.filter(r=>Number(r.rating)===n).length/reviews.length*100:0}%`}}/></div><span>{reviews.filter(r=>Number(r.rating)===n).length}</span></div>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">{d.recentReviews}</h2><div className="mt-4 space-y-3">{reviews.slice(0,5).map(r=><div key={r.reviewId} className="rounded-xl bg-slate-50 p-4"><p className="font-black">{'★'.repeat(Number(r.rating))}{'☆'.repeat(5-Number(r.rating))}</p><p className="mt-1 text-sm">{r.feedback||d.noFeedback}</p><p className="mt-2 text-xs text-slate-500">{r.bookingId}</p></div>)}{!reviews.length&&<p className="text-sm text-slate-500">{d.empty}</p>}</div></section></div>
 <section className="mt-6 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">{d.mapFilters}</h2><div className="flex flex-wrap gap-2">{[['all',d.all],['serviceRequests',d.serviceRequests],['workers',d.workers],['active',d.active],['completed',d.completed]].map(([v,l])=><button key={v} onClick={()=>setMapFilter(v)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${mapFilter===v?'bg-[#16834b] text-white':''}`}>{l}</button>)}</div></div><div className="mt-4"><FederationMap points={visiblePoints}/></div></section>
 </section>
}
export default function AnalyticsPage(){return <AuthGuard role="federation"><FederationShell><Content/></FederationShell></AuthGuard>}
