'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import AuthGuard from '../../../../components/AuthGuard';
import FederationShell,{useFederationData} from '../../../../components/FederationShell';
import {phase13,Lang,t} from '../../../../locales';
const flow=['REQUESTED','ASSIGNED','ACCEPTED','ON THE WAY','ARRIVED','INSPECTION','ESTIMATE','SERVICE','COMPLETED'];
export default function RequestDetail(){return <AuthGuard role="federation"><FederationShell><Content/></FederationShell></AuthGuard>}
function Content(){const {id}=useParams<{id:string}>();const {bookings}=useFederationData();const [lang,setLang]=useState<Lang>('en');useEffect(()=>setLang((localStorage.getItem('sahyogsetu-language')||'en') as Lang),[]);const d=phase13[lang]||phase13.en;const b=bookings.find(x=>x.id===id);if(!b)return <section className="mx-auto max-w-4xl px-4 py-10"><p>{d.noData}</p></section>;const idx=flow.indexOf(b.status);return <section className="mx-auto max-w-4xl px-4 py-6"><Link href="/federation/requests" className="text-sm font-bold text-[#16834b]">← {d.requests}</Link><div className="mt-4 rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-slate-500">{d.bookingId}</p><h1 className="text-2xl font-black">{b.id}</h1></div><span className="rounded-full bg-green-50 px-3 py-2 text-xs font-black text-[#16834b]">{b.status}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[[d.service,(t[lang]||t.en).services.items[b.service]||b.service],[d.requirement,b.requirement],[d.customerArea,b.location||'—'],[d.date,b.date||'—'],[d.requestTime,b.time||'—'],[d.worker,b.worker||d.unassigned],[d.estimate,b.estimateStatus||b.estimate?.status||'—'],[d.payment,b.paymentStatus||'—']].map(([a,v])=><div key={a}><p className="text-xs font-bold uppercase text-slate-400">{a}</p><p className="mt-1 font-bold">{v}</p></div>)}</div><h2 className="mt-8 text-xl font-black">{d.timeline}</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{flow.map((state,i)=><div key={state} className={`rounded-xl border p-3 ${i<=idx?'border-green-200 bg-green-50':'bg-slate-50'}`}><span className="text-xs font-black">{i<=idx?'✓':'○'} {state}</span></div>)}</div></div></section>}
