'use client';
import {useEffect,useMemo,useState} from 'react';
import AuthGuard from '../../../components/AuthGuard';
import FederationShell,{useFederationData,availability,workers} from '../../../components/FederationShell';
import {phase13,Lang,t} from '../../../locales';
import {readVerification} from '../../../lib/profiles';
const baseAreas=['Kothrud','Baner','Wakad','Shivajinagar','Hadapsar','Katraj'];
export default function ServiceAreas(){return <AuthGuard role="federation"><FederationShell><C/></FederationShell></AuthGuard>}
function C(){const{bookings}=useFederationData();const[lang,setLang]=useState<Lang>('en'),[selected,setSelected]=useState('Kothrud');useEffect(()=>setLang((localStorage.getItem('sahyogsetu-language')||'en') as Lang),[]);const d=phase13[lang]||phase13.en;const items=(t[lang]||t.en).services.items;const rows=useMemo(()=>baseAreas.map(area=>{const ws=workers.filter(w=>readVerification(w.id).serviceAreas.includes(area));const bs=bookings.filter(b=>String(b.location||'').toLowerCase().includes(area.toLowerCase()));const counts:Record<string,number>={};bs.forEach(b=>counts[b.service]=(counts[b.service]||0)+1);return {area,ws,bs,counts}}),[bookings]);const cur=rows.find(x=>x.area===selected)||rows[0];return <section className="mx-auto max-w-7xl px-4 py-6"><h1 className="text-3xl font-black">{d.serviceAreas}</h1><div className="mt-6 grid gap-4 md:grid-cols-3">{rows.map(x=><button key={x.area} onClick={()=>setSelected(x.area)} className={`rounded-2xl border bg-white p-5 text-left ${selected===x.area?'border-green-400 ring-2 ring-green-100':''}`}><h2 className="font-black">{x.area}</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span>{d.regionalWorkers}: <b>{x.ws.length}</b></span><span>{d.availableWorkers}: <b>{x.ws.filter(w=>availability(w.id,bookings)==='AVAILABLE').length}</b></span><span>{d.activeRequestsArea}: <b>{x.bs.filter(b=>b.status!=='COMPLETED'&&b.status!=='CANCELLED').length}</b></span><span>{d.completedRequestsArea}: <b>{x.bs.filter(b=>b.status==='COMPLETED').length}</b></span></div></button>)}</div>{cur&&<div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">{cur.area} — {d.areaDetails}</h2><p className="mt-2 text-sm text-slate-500">{d.supportedServices}</p><div className="mt-3 flex flex-wrap gap-2">{Array.from(new Set(cur.ws.map(w=>w.service))).map(s=><span key={s} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold">{items[s]||s}</span>)}</div><h3 className="mt-6 font-black">{d.mostRequested}</h3><div className="mt-3 space-y-2">{Object.entries(cur.counts).sort((a,b)=>b[1]-a[1]).map(([s,n])=><div key={s} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{items[s]||s}</span><b>{n}</b></div>)}{!Object.keys(cur.counts).length&&<p className="text-sm text-slate-500">{d.noData}</p>}</div></div>}</section>}
